### ISSUE TITLE
Split mingw32/64 runs

### ISSUE THREAD

**Issue by lazka** [msys2/msys2-autobuild#12]
Long term: In theory we can built everything separately there. Which means it's less likely that we run out of time or out of disk space.

**Comment by eine** [comment]
Does this mean that packages which work for MINGW32 or MINGW64 only might be allowed in the future?

**Comment by lazka** [comment]
It would make it easier at least

**Comment by lazka** [comment]
This becomes more important if we go ahead and start adding targets for ucrt and clang. I'll adjust the API next to expose the build targets (msys/mingw32/mingw64) for each package and dependency.

**Comment by lazka** [comment]
done -> https://github.com/msys2/msys2-autobuild/runs/1130299788?check_suite_focus=true
