### ISSUE TITLE
[Feature request] Don't require github credentials for fetch-assets

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/msys2-autobuild#20]
`autobuild.py fetch-assets` works perfectly well without github credentials, but the script requires either `GITHUB_TOKEN` or `GITHUB_USER`/`GITHUB_PASS` environment variables to be set.  Rather than deal with credentials, I use the following stupid hack:

```diff
diff --git a/autobuild.py b/autobuild.py
index 2df03ba..55acaeb 100644
--- a/autobuild.py
+++ b/autobuild.py
@@ -750,7 +750,8 @@ def get_credentials() -> Dict[str, Any]:
     elif "GITHUB_USER" in environ and "GITHUB_PASS" in environ:
         return {'login_or_token': environ["GITHUB_USER"], 'password': environ["GITHUB_PASS"]}
     else:
-        raise Exception("'GITHUB_TOKEN' or 'GITHUB_USER'/'GITHUB_PASS' env vars not set")
+        return {}
+        #raise Exception("'GITHUB_TOKEN' or 'GITHUB_USER'/'GITHUB_PASS' env vars not set")


 def get_repo() -> Repository:
```

It would be nice if it knew not to require credentials for operations that can be done unauthenticated.

**Comment by lazka** [comment]
There is a 60 API calls rate limit for anonymous requests, which isn't much. So we probably have to catch those errors an suggest setting GITHUB_TOKEN etc..

**Comment by jeremyd2019** [comment]
I haven't hit any error like that, but I do get fairly frequent timeout errors and have to restart the command.  I don't know if that's related to an anonymous request limit or just my internet connection though.
