### ISSUE TITLE
how to run msys2-autobuild in a fork?

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/msys2-autobuild#32]
I am thinking about playing with the [self-hosted ARM64 Windows runner](https://github.com/actions/runner/pull/785), and also it would be cool to use a version of autobuild for i686 msys2 packages instead of my current manually-invoked process.

From what I could tell, this project seems fairly tightly coupled to [msys2-web](https://github.com/msys2/msys2-web) for its data on what to process, so it doesn't seem as simple as just making a fork and starting it running.  Could you provide some notes on what would be required to make an autobuild fork run?

**Comment by lazka** [comment]
Let me clean up the code a bit

**Comment by jeremyd2019** [comment]
no rush, just some curiosity to play with.

**Comment by lazka** [comment]
A bit better now: https://github.com/msys2/msys2-autobuild/blob/master/autobuild.py#L37

There is the assumption though that it handles msys packages, because mingw ones can depend on that. But in theory if you change `MINGW_ARCH_LIST `, `MINGW_SRC_ARCH` and `REPO` it should maybe work.

**Comment by jeremyd2019** [comment]
Had to create a PAT (not sure what rights to give it, just gave it public repos, might not even have needed that) and put in repo secrets GITHUBTOKENREADONLY.  Then I had to create releases staging-{mingw,msys,failed} and status.  Then it seemed able to run 'schedule'

**Comment by lazka** [comment]
In theory it should fall back to `GITHUB_TOKEN`: https://github.com/msys2/msys2-autobuild/blob/78b3da87270a689f9d07979491c55e3eb151b4f8/autobuild.py#L1239

Only downside being that you are limited to 1000 requests/h, but that should be enough for one build type.

**Comment by jeremyd2019** [comment]
In theory, but in practice it failed for me getting the workflow

**Comment by jeremyd2019** [comment]
> In theory, but in practice it failed for me getting the workflow

I think if the secret is not set ,the workflow will set the GITHUB_TOKEN_READONLY var in the env to an empty string?

**Comment by lazka** [comment]
ah, true, would `${{ secrets.GITHUBTOKENREADONLY || secrets.GITHUB_TOKEN }}` work?

**Comment by jeremyd2019** [comment]
I think either would work, as long as `secrets.GITHUBTOKENREADONLY` isn't something stupid like 0 😉

**Comment by jeremyd2019** [comment]
I finally got around to nuking the PAT from the secrets of my fork, and this now works falling back to the GITHUB_TOKEN
