### ISSUE TITLE
python cache key should include python arch

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/msys2-autobuild#36]
Currently the actions/cache action is https://github.com/msys2/msys2-autobuild/blob/de1083d03e6ee7f310ba8a2a29a60ea27b6f5978/.github/workflows/build.yml#L89-L94

If actions/runner#1185 were implemented, I would change this to `${{ runner.os }}-${{ runner.arch }}-pip-`.  I don't know that it's worth adding yet another `startsWith(matrix.name, 'clangarm')` for it though, because the self-hosted runner already still has the pip cache (and in fact the per-user python modules) between runs.

**Comment by lazka** [comment]
we could just use `matrix.name`

**Comment by jeremyd2019** [comment]
true, but then all the runners on x64 couldn't share the cache.

**Comment by lazka** [comment]
I'm wondering, is there a problem with x64/aarch64 sharing the cache? The wheels should all contain their arch in the filename, and the slight duplication shouldn't hurt much..

**Comment by jeremyd2019** [comment]
Doesn't hurt much, no, just downloads wheels it won't use, and then downloads the ones it does want.
