### ISSUE TITLE
Switching to "main mirror" now a no-op?

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/msys2-autobuild#47]
https://github.com/msys2/msys2-autobuild/blob/a0a0b3f47b5c5e9e09e42ae9261ee230dfbd2da6/.github/workflows/build.yml#L125-L126

This will not match anymore now that the include lines are all `mirrorlist.mingw`.  Given that nobody noticed, this may not actually be necessary anymore now that mirror.msys2.org is the 'default' mirror?

**Comment by lazka** [comment]
There is a tiny chance that after an update of repo.msys2.org we parse the repo, but mirror.msys2.org still doesn't know about it and redirects to an outdated mirror, so in theory it is still needed, though very unlikely that there are any bad consequences.
