### ISSUE TITLE
Don't install VCS globally for building source packages

### ISSUE THREAD

**Issue by lazka** [msys2/msys2-autobuild#69]
The problem is that makepkg doesn't handle make dependencies when building source packages, so we have to install them manually before. We need to figure out how to install them and restore the previous state some other way.

**Comment by MehdiChinoune** [comment]
I think a good solution is to make a separate job `mingw-src` for building source packages (not under ucrt64).

**Comment by lazka** [comment]
thanks, yeah, that might be an easier fix in the short run

(in the long run it conflicts with https://github.com/msys2/msys2-autobuild/issues/57 which would build anything in every job)

**Comment by lazka** [comment]
done in 2ae439cd008239db
