### ISSUE TITLE
Use only one job for building src without queue

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/msys2-autobuild#74]
I don't think src requires more than one job, and I think also It could built without queue.

**Comment by lazka** [comment]
> I don't think src requires more than one job

good idea

> and I think also It could built without queue.

what do you mean by that?

**Comment by lazka** [comment]
I see.

I'm not sure if that's worth it.. I don't want to assume what tools `prepare()` etc use and use old versions.

But I know what you mean.. the different speeds lead to lots of ping pong between build types. I'll think about it.

**Comment by lazka** [comment]
What if we run "src" jobs after all the other jobs?

**Comment by lazka** [comment]
I've reduced the build interval recently, to improve things a bit at least: 3116e844bee9bb
