### ISSUE TITLE
Is the ARM runner provided by osuosl?

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/msys2-autobuild#84]
@jeremyd2019 In https://osuosl.org/services/aarch64/current-projects/ they metion MSYS2.
Is it true. Just to make sure.

**Comment by jeremyd2019** [comment]
No.  I got access to their aarch64 openstack, but I couldn't get it to work out either technically or licensing-wise to be able to run Windows on it.  I wound up with the MS Dev Kit instead, which has Hyper-V.

**Comment by MehdiChinoune** [comment]
So, I think you/we should tell them to remove MSYS2 from that list.

**Comment by lazka** [comment]
I've filed a PR for this: https://github.com/osuosl/osuosl-pelican/pull/585

**Comment by MehdiChinoune** [comment]
I have already sent them an email about it, They replied by asking @jeremyd2019 if he wants to.
```
Jeremy: Do you want us to go ahead and remove your access and account?
```

**Comment by lazka** [comment]
Maybe offtopic, https://github.blog/changelog/2024-03-04-github-actions58-larger-runners-windows-11-beta/ they now have beta Win11 images, so I guess they have figured out the licensing, at least for themselves.

**Comment by MehdiChinoune** [comment]
We didn't get a final answer from either sides.

**Comment by lhmouse** [comment]
Can MSYS2 run in Wine?

**Comment by MehdiChinoune** [comment]
> Can MSYS2 run in Wine?

It has some issues https://github.com/msys2/MSYS2-packages/issues/682

**Comment by lhmouse** [comment]
> > Can MSYS2 run in Wine?
> 
> It has some issues [msys2/MSYS2-packages#682](https://github.com/msys2/MSYS2-packages/issues/682)

Linaro offers a docker image with prebuilt wine-arm64: https://linaro.org/blog/emulate-windows-on-arm/

I have pulled the image locally, and it is Debian on AMD64, with Wine ARM64 emulated by QEMU. So in theory we can install both Wine AMD64 and Wine ARM64. The AMD64 Wine run MSYS2 and the ARM64 Wine can run CLANGARM64 tools.

**Comment by lazka** [comment]
There is a wine fork that in theory allows running cygwin: https://gitlab.winehq.org/jhol/wine/-/commits/msys2-hacks-17 (note that the branch name changes on each rebase)
